fix(Command) - props.value is possibly null (#1164)
adds nullish coalescing operator to default nullish vaue props to empty string

src/components/ui/command/CommandItem.vue:48:62 - error TS18047: 'props.value' is possibly 'null'.